# Mirai Api HTTP
API_VERIFY_KEY = ''
API_HOST = '192.168.2.221'
API_PORT = 5700

# admin
ADMIN_QQ = []

# bot
BOT_QQ = 0
GROUP = []
STARTS_WITH = '.'
MAX_MESSAGE_RATE = 10
ALERT_MESSAGE_RATE = 5
IF_OVER_MAX_MESSAGE_RATE_MUTE_SECONDS = 60

# Tencent Cloud
QCLOUD_SECRET_ID = ''
QCLOUD_SECRET_KEY = ''